// Responsive WebP variants are generated by `npm run images` (scripts/optimize-images.mjs).
export const IMAGE_WIDTHS = [480, 800, 1024];
export const imageSrcSet = (name) => IMAGE_WIDTHS.map((w) => `/img/${name}-${w}.webp ${w}w`).join(', ');
